### PR TITLE
Allow null/None values for Optional[T] fields

### LINKED ISSUE #108: Error serialisation of Optional field and default value set is not None
```python
from dataclasses import dataclass, field
from typing import List, Optional

import marshmallow_dataclass
import marshmallow.validate


@dataclass
class Building:
    # field metadata is used to instantiate the marshmallow field
    height: float = field(metadata={"validate": marshmallow.validate.Range(min=0)})
    name: str = field(default="anonymous")
    age: Optional[int] = field(default=0)

building_schema = marshmallow_dataclass.class_schema(Building)()
building_schema.load({"name": "Eiffel Tower", "height": 324, "age": None})
```

For above code I am getting this error:-
```bash
    building_schema({"name": "Eiffel Tower", "height": 324, "age": None})
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow_dataclass/__init__.py", line 544, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 724, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/XXX/.venv/lib/python3.7/site-packages/marshmallow/schema.py", line 911, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'age': ['Field may not be null.']}
```

Error is from marshmallow schema, but I am not able to find root cause of the error. Any help would be appreciated.

When `age: Optional[int] = field(default=None)` above code works.

Python 3.7
marshmallow_dataclass tried on 8.0.0 and 8.1.0
marshmallow 3.8.0

### PR DESCRIPTION
**Pull request by noirbee**
Fixes #108

### CODE REVIEW

**Review by sebastien-boulle — APPROVED** [review]

**Comment by lovasoa** [comment]
This looks good ! Can you add the new `allow_none` attribute to the documentation (through the doc comments, and maybe also doctests) ?

**Comment by noirbee** [comment]
> This looks good ! Can you add the new `allow_none` attribute to the documentation (through the doc comments, and maybe also doctests) ?

Updated the commit with a couple of doctest strings, is this what you had in mind ?

**Comment by lovasoa** [comment]
Yes, this is it, thank you !

**Comment by noirbee** [comment]
Hi, is something else needed to get this merged ?

**Comment by lovasoa** [comment]
No, sorry it took time, and thanks again

**Pull request merged**
