### PR TITLE
Use TYPE_MAPPING from base_schema

### PR DESCRIPTION
**Pull request by MartinAltmayer**
I ran the tests with Python 3.6.10, 3.7.7, and 3.8.1. I also tested this branch in my application which uses Python 3.8.1.

### CODE REVIEW

**Comment by MartinAltmayer** [comment]
Thanks for merging! Shall I open a new PR for the README?

**Comment by MartinAltmayer** [comment]
Ok, I saw your own commit. Thanks for updating the README!

**Comment by lovasoa** [comment]
Yes, I updated the README. Thank you for your contribution  @MartinAltmayer ! I am going to update the changelog and publish a new release.

**Comment by lovasoa** [comment]
Hmm... I'm thinking: my example may be super confusing.

```py
class BaseSchema(marshmallow.Schema):
    TYPE_MAPPING = {CustomType: CustomField}
```

creates a schema where **none of the default type mappings apply**. This is probably never what anyone wants.

**Comment by lovasoa** [comment]
Should we update our code to  use `{**base_schema.TYPE_MAPPING, **Schema.TYPE_MAPPING}`, or leave it like that, but change the documentation and the tests ?

**Comment by lovasoa** [comment]
I'd love to hear your opinion @sloria !

**Comment by lovasoa** [comment]
I implemented the first solution. I'll release it once I'm sure everyone agrees. @sloria , @MartinAltmayer ?

**Comment by MartinAltmayer** [comment]
Looks fine to me, the user probably never wants to remove the default mapping.

**Comment by lovasoa** [comment]
Ok, I'll publish that this weekend if no one opposes in the meantime.

**Comment by sloria** [comment]
Yeah, the implemented behavior seems reasonable to me

**Comment by lovasoa** [comment]
OK, it's deployed: https://pypi.org/project/marshmallow-dataclass/

**Pull request merged**
