### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by sloria**
These were found by flake8

### CODE REVIEW

**Comment by sloria** [comment]
If you'd like, I can add flake8 to https://github.com/lovasoa/marshmallow_dataclass/pull/31

**Comment by lovasoa** [comment]
There are no unused imports. You just moved doctest imports inside the doctests, which makes them more verbose. The documentation tests appear in the documentation, and I'd like to keep them as short and to the point as possible.

**Comment by sloria** [comment]
I think adding these imports to the docs actually makes them more clear. As a reader of the docs, seeing the imports makes the snippets more easily reproducible. It also makes the code more clear and prevents linters from complaining.

**Comment by lovasoa** [comment]
Ok, let's merge that

**Comment by sloria** [comment]
Shall I add flake8 to my other PR?

**Pull request merged**
