### PR TITLE
Issue 13: fix forward references

### PR DESCRIPTION
**Pull request by AleksanderPawlak**
Updated version of: https://github.com/lovasoa/marshmallow_dataclass/pull/54
Fix for: https://github.com/lovasoa/marshmallow_dataclass/issues/13

### CODE REVIEW

**Comment by lovasoa** [comment]
thanks, the changes look good ! But the tests are failing...

**Comment by lovasoa** [comment]
I opened an issue upstream: https://github.com/typeddjango/pytest-mypy-plugins/issues/88

**Comment by warwing** [comment]
@AleksanderPawlak Just applied the patch to our project. Thanks a lot for that! Forks like a charm for python 3.9.

**Comment by lovasoa** [comment]
thanks for the pr, and sorry for the delay ! Merged in #186

**Pull request closed without merging**
