### PR TITLE
use polyfield for union

### PR DESCRIPTION
**Pull request by CedricCabessa**
marshmallow-union is not supported anymore and have some known issues
see:
https://github.com/lovasoa/marshmallow_dataclass/issues/67

Author advise to switch to marshmallow-polyfield

### CODE REVIEW

**Comment by MaxRandom** [comment]
Hi @lovasoa!
Could you review this PR, please? Really need it :)

**Comment by YBadiss** [comment]
Would be very useful to us! 👍

**Comment by CedricCabessa** [comment]
hey @lovasoa :wave: 

Have you got a chance to look at this patch?

If you're afraid that it will break existing code, I was thinking that maybe we can keep marshmallow_union and use marshmallow_polyfield only if the module is available. This way it will be transparent to user and we can get more feedback until we are really confident.

Let me know what you think and how we can help :-)

No pressure here, cheers

**Comment by lovasoa** [comment]
Hello, and sorry for not answering earlier. I had a look at the pull request. I'm not sure integrating with marshmallow-polyfield is a great idea. It is a ~90 LOC library that doesn't handle Fields, only Schemas. Creating an intermediary schema with a single field works, but it requires more code than just writing the whole feature from scratch, and I don't think this is the kind of code we want to be maintaining long term. I think the path forward is to fix existing bugs in [python-marshmallow-union](https://github.com/adamboche/python-marshmallow-union), and add support for type-based disambiguation to it. If it's not possible, than we should create a separate marshmallow union library that supports disambiguating fields based on their type. This library would be generally useful even outside of marshmallow-dataclass. 

We could then write code such as : 

```python3
UnionField([
  TypeCheckingField(int, Integer)
  TypeCheckingField(str, String)
])
```

**Comment by CedricCabessa** [comment]
Yes `marshmallow-polyfield` is not ideal and I agree a clean marmallow library could be better.
However this will take time, and I far as I understand, `marshmallow-union` is [dead](https://github.com/adamboche/python-marshmallow-union#warning)

In the meantime, I can propose another solution (see last commit)
 * If marsmallow-polyfield is present, just use it. This help in some case as the unit test show.
 * if marsmallow-polyfield is not present, we stick to marshmallow-union, so no user should break and nobody have to change dependencies.

**Comment by lovasoa** [comment]
I opened an issue in marshmallow-union to offer help with the maintenance: https://github.com/adamboche/python-marshmallow-union/issues/34

As I was saying, I really don't think writing a wrapper for polyfield is worth it at all: writing the serialization and deserialization logic from scratch would represent less code and be less hacky.

**Comment by CedricCabessa** [comment]
ok, thank you
I'll follow the issue closely :-)
Feel free to close the PR if you want

**Comment by lovasoa** [comment]
I think the tests you wrote are good. I'll merge them when we implement a solution to this issue.

**Pull request closed without merging**
