### PR TITLE
Fix compatibility with older python versions

### PR DESCRIPTION
**Pull request by lovasoa**
#132 broke compatibility with python 3.6

### CODE REVIEW

**Comment by lovasoa** [comment]
Since the majority of users are on python 3.6, this is pretty critical

**Comment by anis-campos** [comment]
Good to know that it wasn't too bad.  🤔  I was actually wondering why I had to fall back to `collections.abc.xxx` to check the types.

**Comment by anis-campos** [comment]
TIL that there is implementation difference in the `typing_inspect.get_origin` method across the some python versions.

**Comment by lovasoa** [comment]
See https://docs.python.org/3/library/stdtypes.html#types-genericalias

**Pull request merged**
