### PR TITLE
Improve how union fields are handled

### LINKED ISSUE #67: Union dump not working
Hi,
I have noticed the dumping of a Union type is returning an empty object:

```py
from marshmallow_dataclass import dataclass
from typing import List, Union

@dataclass
class Vector:
    x: float
    y: float

@dataclass
class Point:
    x: float
    z: float


@dataclass
class Geometries:
    elements: List[Union[Point, Vector]]

pts = Geometries.Schema().load({"elements": [
    {"x": 1, "y": 1},
    {"x": 1, "z": 1},
]})
schema=Geometries.Schema()
print(schema.dump(schema.load({"elements": [
    {"x": 1, "y": 1},
    {"x": 1, "z": 1},
]})))
```
gives
```py
{"elements": [{}, {}]}
```
but should again return
```py
{"elements": [
    {"x": 1, "y": 1},
    {"x": 1, "z": 1},
]}
```

### PR DESCRIPTION
**Pull request by lovasoa**
Closes #86
Closes #67

### CODE REVIEW

**Comment by lovasoa** [comment]
This is an alternative to #86. 

 - **pros** : It avoids the dependency to polyfield, the hack of having to define a one-field schema for each union field, and most importantly the need to run *both* serialization and deserialization every time a field is serialized or deserialized.
 - **cons** : `Union[int,str]` will deserialize `"42"` as `42`. This is not technically incorrect, but may be surprising. This is because [`marshmallow.fields.Integer`](https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Integer) accepts string representations of integers. More generally, the types are checked only after deserialization, so if a field in the union accepts a certain input and generates a valid output for it, then it will be used.    

@CedricCabessa, let me know what you think.

**Comment by CedricCabessa** [comment]
Hey @lovasoa , thank you for this it look awesome!

Just about 

> This is easy to work around by creating strict versions of fields. For instance, fields.Integer accepts a strict parameter that can be set to True.

My solution is the following:

```
class StrictInt(Integer):
￼    def __init__(self, *args, **kwargs):
￼        kwargs["strict"] = True
￼        super().__init__(*args, **kwargs)

class CustomSchemaStrict(marshmallow.Schema):
    TYPE_MAPPING = {
        **marshmallow.Schema.TYPE_MAPPING,
        int: StrictInt,
    }

@dataclass(base_schema=CustomSchemaStrict)
class MyClass:
   foo: Union[int, str]
```

I'm wondering if you had something simpler in mind ?

I've done some test with your version, so far it is good :+1:

**Comment by lovasoa** [comment]
It depends on your usage, but if you want to keep the general behavior of accepting strings for integers in general, and just override it in some places where it could cause confusions (to follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle)), you can define a [`NewType`](https://github.com/lovasoa/marshmallow_dataclass#custom-newtype-declarations) : 

```python
StrictInt = NewType("StrictInt", int, strict=True)

class MyClass:
   foo: Union[StrictInt, str] # This will deserialize integers to int and strings to str
   bar: int # This will still accept strings
```

**Comment by CedricCabessa** [comment]
ok, understood!
LGTM

**Pull request merged**
